# story text and choice blocks for each room:

# INTRODUCTION / OUTSIDE THE FORTRESS

intro = "\nYou find yourself standing deep in a dark forest. The trees soar overhead, seeming to be impossibly tall, blocking out any hint of sunlight - if indeed it is even day. The air is cool and mist seems to waft between the massive tree trunks. Does it move faster each time you look away from it? You don't really remember how you got here... huh. But you do remember what you're supposed to be doing: retrieving a treasure from an abandoned fortress in the darkest part of the Haunted Weald. No one quite knows what this treasure is, but you know it is vital that you find it. A moldering stone edifice stands before you, something built and then lost, forgotten and never returned to. Moss and creepers almost hide the structure entirely, but a door - oddly pristine amongst all the plants growing up and upon it - stands a few paces ahead of you. Something shrieks deeper in the forest - it could be the call of a hunting cat... or maybe what is being hunted. What do you do? \n"

intro_return = "\nYou leave the fortress, finding yourself back in the Haunted Weald. It looks as dark, foreboding, and unwelcoming as it did when you first found yourself standing there. At least there is nothing shrieking this time. Though... did you just hear something rustling in those bushes? What do you do? \n"

intro_choices = "\n1. Flee! No way you're going in there! Are you crazy?! \n2. Enter the fortress. Someone has to find the treasure, right? \n"

intro_choices_return = "\n1. Flee! No way you're going back in there! Are you crazy?! \n2. Re-enter the fortress. Someone still has to find the treasure, right? \n"

run_away = "\nYou don't like the sound of the creatures out here, the darkness of the forest, or the shiftiness of the mist out of the corner of your eyes. And you -definitely- don't like the look of this creepy old fortress and its inexplicably inviting door. It doesn't matter how important this mysterious treasure is. Nope, no way. You are outta here! You take off at a run away from the fortress and hopefully back towards town. Or at least some sunlight. Unfortunately for you, whatever was shrieking deeper in the forest was not the only one of its kind. You don't even see what hits you as something drops out of the trees, and you add a shriek of your own to the quiet of the forest before your world goes dark. \n\nSadly, there is one less {0} in the world. But it seems unlikely anyone will ever find your unmarked grave in the depths of the Haunted Weald. \n\nThe End.\n"


# FORTRESS ENTRANCE / START OF UPPER HALLWAY

enter_fortress = "\nYou might not remember getting here, but you do know you need to find the treasure. And surely whatever is inside the fortress can't be nearly as bad as whatever that thing was. This ruin has been abandoned for centuries. Everything should be dead in there. ... Right? Before you can think much harder about that, you urge your feet into moving and step up to the door. It swings open with the barest whisper of sound almost before you touch the handle. Ooookay, then, that's not creepy at all. You step inside and this time the door -definitely- moves without being touched, shutting firmly behind you. Well. \n\nDespite being unable to locate any flames, the inside of the fortress is dimly lit with subtly shifting light. Dark shadows gather in the corners, more thickly than it seems like shadows should. You eye them uncertainly, but nothing lunges forth. All the same, each time you glance away you feel sure something moved just barely out of your line of sight. But the sourceless illumination reveals your surroundings well enough. A sturdy wooden door stands to your left, hanging slightly ajar, though it shows nothing of the room beyond. The corridor you stand in, wide enough for three men to walk abreast, stretches further off into the fortress ahead of you. And to your right is a short hallway following the exterior wall of the fortress. By the deepening shadows at the end, it looks like it might lead to a staircase. What do you do? \n" 

enter_fortress_return = "\nYou find yourself back at the entrance of the fortress, that slightly-too-helpful door that is probably magic behind you. To your left you see a solid wooden door standing ajar. Ahead, the corridor leads you further into the fortress. To your right is a short hallway, the far end of which is populated with a host of dark shadows and perhaps the first step of a staircase... What do you do? \n"

enter_fortress_choices = "\n1. Enter the partially open door to the left. \n2. Continue down the hallway. Time to have a look around further in. \n3. Investigate the hallway... Maybe don't think too hard about how dark those shadows are. \n4. Maybe this was a bad idea... go back outside. \n"


# GUARD ROOM

guard_room = "\nYou decide to have a look through the door. You ease up to it, reaching out to push the door slowly open. This time the door does nothing to help you out - it takes more muscle than you first anticipated before the door grinds reluctantly open with a raspy scrape of wood over stone. Having decided nothing is going to jump out of the shadows at you, you step further into the room to have a look around. The square room is rather unremarkable all in all. A thin layer of dust softens the stone floor and coats the few items left in the room. Against the back wall a spindly cot has collapsed in upon itself. A couple of stools are gathered around a low table to your left. The table still holds a pitcher and a few wooden cups. One stool has been knocked over and never picked up. To your right you see a weapons rack bolted onto the wall - empty now of the spears it probably once held. It looks like maybe this was the guard's room. Not much to see here. As you start to turn back to the door, a faint metallic gleam catches your eye in the corner near the weapons rack. Huh. Looks like a crowbar. What do you do? \n" 

guard_room_return_with_crowbar = "\nThe wooden door seems to have fallen half shut behind you when you left previously. When you shove it open again it moves a bit easier than it did the first time, but there isn't anything new to see in the guard room. The dust laying thickly on the stone of the floor has been disturbed by your boots, and there is an empty corner where the crowbar was propped. But the table and stools sit undisturbed and the cot - probably used for snatching a bit of rest, sanctioned or otherwise - is in the same sorry state of disrepair. What do you do? \n"

guard_room_return_no_crowbar = "\nThe wooden door seems to have fallen half shut behind you when you left previously. When you shove it open again it moves a bit easier than it did the first time, but there isn't anything new to see in the guard room. The dust laying thickly on the stone of the floor has been disturbed by your boots, and the crowbar is still propped in the corner near the empty weapons rack. The table and stools sit undisturbed and the cot - probably used for snatching a bit of rest, sanctioned or otherwise - is in the same sorry state of disrepair. What do you do? \n"

guard_room_choices = "\n1. Grab the crowbar before you head back into the corridor. You never know when that might come in handy. \n2. Leave the room and don't disturb the dust. Who knows what spirits might be attached to that crowbar. \n"

guard_room_choices_crowbar = "\n1. Head back into the hall. Nothing more to be seen here. \n"


# ROUND HALL

round_hall = "\nYou head down the corridor and deeper into the dim fortress. The stone is pitted and seems to be crumbling to sand in patches. It's almost as if the fortess is slowly rotting away from the inside out. The shiftiness of the dim light and the shadows you would swear won't quite stay still give a surreal cast to the passage. Maybe this is all a dream. Why are you here getting this treasure anyways? Who is it important to? Questions for afterwards, perhaps. The hallway dumps you out into an expansive, round room. An arched ceiling soars overhead. The delicate, twisting columns supporting its weight are evenly spaced in a ring a few paces in front of the wall. Behind the columns there seem to be traces of color on the walls, but whatever art adorned them has long since faded into obscurity with the passage of time. As you walk further in, you notice a domed skylight in the very center of the roof - the glass is remarkably intact despite the crumbliness of the fortress otherwise. On the floor below is an elaborate mosaic. In better times, perhaps sunlight would have streamed through in a solid column, illuminating the swirling stonework and making its riot of colors brighten the space. Now, though, no light falls through the glass, only the murk of the Weald. The colors of the mosaic are dusty and darkened with age. Faint motes of dust float in the air like spirits of the once-residents, stirred to a half-life again by the passage of your steps. The quiet begs not to be disturbed in this space and even your breathing seems too loud. \n\nTo your left is an elaborate doorway, stone foliage so realistic you expect it to move decorating the frame of it in vines, leaves and fragile flowers. The overlarge doors are pushed open already, and you can just make out bits of something in the room. Ahead of you is an equally large doorway, though this one is more restrained in its elegance, subtle curves and swirls of stone making the frame of the door appear to loom larger. You can see glints of gilding where it still stubbornly clings to a few patches of stone. One door stands closed, the other seems to have fallen off its hinges and into the room beyond. To your right is a more normal sized doorway, its frame in keeping with the elegance of the space, but nothing to compare with the other two. What do you do? \n" 

round_hall_return = "\nThe hushed silence of the round hall is pervasive, the dust muffling the passage of your boots over the mosaic set in the floor as if cautioning you to silence. The elaborately carved, floral doorway stands to your left - as breathtakingly life-like as when you first caught sight of it. The doors to the room stand open. Ahead of you stands an equally oversized doorway that looks just as finely crafted, if a bit more subdued in its design, the glint of gold on it just visible from a distance. One door has fallen - or was snapped? - off its hinges and into the room. To your right stands a normal sized doorway. One that is not out of place amongst the elevated decor of the hall, but doesn't quite reach the artistic heights of the other two doorways. What do you do? \n"

round_hall_choices = "\n1. Head to the left. That otherworldly carving begs a closer look. \n2. Go straight across the round room. That looks like a grand doorway, with gold on it no less. Maybe it leads to the treasure room? \n3. Turn right. Sometimes the most interesting things are behind the most unassuming doors. Isn't that how that saying goes? \n4. Return to the hallway behind you. Maybe a different route would be best. \n"


# SHRINE

shrine = "\nYou set your steps towards the flowering doorway, trying not to tread too heavily on the way. The closer you get to the doorway, the more convinced you are that those carvings couldn't possibly be stone. They are as thin as real plants, each miniscule detail, each pore on the leaves, each thorn on the roses included. You reach out to touch it, but hesitate a hair's breadth away from doing so. Maybe some mysteries are best left unsolved. If it crumbled beneath your fingers the world would have lost a bit of artistry unlike any other. Once you can tear your eyes away from the flowers, you step through the pale doors, crafted of some wood so pale as to be almost white. The room beyond seems... lighter. Those ever-present darker-than-normal shadows seem to avoid this space, the ones that do linger in the deepest corners seeing thin and light in comparison. The floor is as pale as the doors, and the dust seems to have settled less heavily here. The high ceilings above are... are glass again. This time in varying dark hues that seem random until you notice a subtle pattern running through it - one that seems to change each time your attention shifts. You can imagine how stunning it might have been under the sun. Now, as in the previous room, all is dark and dim. THe dark depths of the Haunted Weald smothering any sunlight long before it touches the glass. \n\nYour attention shifts to the end of the long room and there, standing larger than life size in an alcove, is a woman. A goddess. Or at least the statue of one. But the same skilled hands of the sculptor who carved the doorway must have been set to the task of depicting this ethereal figure. You can almost imagine her robes rustling in an unfelt breeze. Her hair seems to float weightlessly around her shoulders. Her eyes are closed, even the long eyelashes resting against her cheek depicted flawlessly. Any moment now she ought to finish the step she's just started to take, open her eyes and ask who disturbs her hushed chamber. You move closer until you find yourself standing a scant pace from her. The white marble seems faintly... luminescent. Or maybe it is your imagination. A short inscription is carved into the stone below her bare feet: 'Hope springs eternal and rewards your faith.' One hand is tucked to her chest, gently clasping a black stone key in her grip. The other hand is extended loosely towards you, palm up and fingers loosely cupped. She is stunningly beautiful. And almost as eerie as she is elegant. That feeling that she might awaken returns stronger than ever. You feel like you don't belong here in front of her. What do you do? \n"

shrine_return_with_key = "\nYou can't help but wonder at the carving on the doorway as you near it again. It is just so... alive. It seems like it wants only a breeze and a bit of sunlight to jump back to life. After a few moments spent marveling, you move past it, back into the shrine. Your eyes fall first to the statue of the woman, just... just making sure she's still where you left her. You are still convinced she is stone, and you are equally convinced that she moved once and might again. But as you move a bit closer the goddess seems to have remained still, the stone seed clutched delicately in one hand. As impossibly lifelike as the plants on the doorway, her ethereal presence fills the faintly multi-hued hall. It feels like she is watching you, even with her eyes closed... What do you do? \n"

shrine_return_no_key = "\nYou can't help but wonder at the carving on the doorway as you near it again. It is just so... alive. It seems like it wants only a breeze and a bit of sunlight to jump back to life. After a few moments spent marveling, you move past it, back into the shrine. Your eyes fall first to the statue of the woman, standing at the far end of the hall. The black stone of the key she holds seems all the darker against the faintly luminescent white of the rest of the sculpture. You can't help but feel like she is watching you approach, despite her closed eyes. Beneath her bare feet, the stone inscriptions reads 'Hope springs eternal and rewards your faith.' As breathtaking as the woman is to look upon, you feel like your presence is unwelcome before her. What do you do? \n"

shrine_choices = "\n1. Take the key before you go. It looks like it could be important. \n2. You decide you should probably leave the key where it is and head back to the round hall. \n"

shrine_choices_key = "\n1. Return to the round hall. As enchanting as the statue of the woman is to look upon, that eerie feeling of being watched hasn't faded. \n"

shrine_trade_key = "\nHesitantly, with your attention half on the woman's face in case those pale eyes -do- open, you reach out to take the key. Despite her seemingly loose hold on it, it doesn't move. You stare a moment, eyes falling to the inscription. That stone seed you found in the barracks is remarkably lifelike... and perhaps a symbol of hope? You place it in the statues open hand and nearly jump out of your skin as the fingers of the statue tighten its grip in the seed, even as she loosens her hold on the key. Heart pounding, you hurriedly grab the key before she changes her mind and beat a hasty retreat out of the statue's field of vision and into the round hall again before you take a breath."

shrine_key_stuck = "\nHesitantly, with your attention half on the woman's face in case those pale eyes -do- open, you reach out to take the key. Despite her seemingly loose hold on it, it doesn't move. You stare a moment, eyes falling to the inscription. Maybe she wants something in return? You're not sure what but it feels like she is waiting for you to do something... What do you do? \n"

shrine_options_stuck_key = "\n1. You don't imagine a second attempt will dislodge the key. And you're not sure you want to test the good will of the statue twice... head back to the round hall.\n"


# RECEPTION ROOM

reception_room = "\nThe huge scale of the doorway ahead of you must mean it's an important room. An important room for an important treasure, you hope? Stepping softly, you creep across the round hall, approaching the half-opened doors. The glint of gold that caught your eye from further away is patterned with silver, gone dark with tarnish, and copper, now a deep green. It must have shone wonderfully when it was kept up, glittering in the sunlight that would have slanted through the dome. The iron bound doors look impressively sturdy, upright or not. You have to wonder how only one of the things came crashing down - what a sound that would have made. Does it... look like it was struck in the middle? You decide not to ponder that for too long and step over the door into the room. It is an imposing space indeed - the ceiling is high, and the space wide... and mostly empty. As you head further into the room, you see a raised dais. But nothing more. Whatever once graced it is gone and it stands empty. Hopefully it wasn't the treasure you are seeking... The shadows seem darker on this end of the room, creeping further away from the walls and corners, stretching imperceptibly towards that low platform. You shiver and think it might be best to go. What do you do? \n"

reception_room_return = "\nAs you step over and past the fallen door, you can't help but think again that it looks a bit like the door was struck in the center... huh. Do the hinges on this side seem wrenched, too? The room is still empty save for the low dais at the far side of the room. It seems small compared to the sweeping height of the room, but its importance seems evident all the same. You mark the gathered shadows at that end of the room as you step a bit closer. They seem to be reaching out for the dais, despite the fact that they are still when you look directly at them. It sends a shiver up your spine. What do you do? \n"

reception_room_choices = "\n1. That wasn't nearly as treasure-filled as you had hoped. You glance back at the shadows to make sure they stay put before you head back to the round hall. \n"


# ROOM TO STAIRS

room_to_stairs = "\nAlthough the other oversized doors are impressive in their grandeur, it would probably make more sense to hide a treasure somewhere less conspicuous. You carefully leave behind the hushed silence of the round hall, heading to the right and stepping through the most human-sized doorway. What awaits you is not a treasure, sadly. In fact, contrary to your high hopes, this room seems to live up to its door in every way. It is square, bare, and almost entirely uninteresting. Except for the fact that on the opposite side of the room there is the beginning of a set of stairs heading downwards, shrouded in shadows that seem to be untouched by the uncanny illumination of the fortress. Hm. What do you do? \n"

room_to_stairs_return = "\nThe square, bare room still boasts little more than a few lingering shadows haunting the corners. On one side of the room, though, the shadows seem to have gathered, clustering thickly at what looks to be the top of a set of stairs down. The other door is far less ominous, opening out into a larger space. What do you do? \n"

room_to_stairs_choices = "\n1. You're not very fond of the look of those shadows. But you take a breath and steel yourself before starting towards the stairs. \n2. The shadows in the fortress do seem restless and unbound by the usual laws of light and shadow... maybe you won't mess with these ones. Go back to the round hall.\n"


# LOWER CORRIDOR

lower_corridor = "\nYou hesitate at the top of the stairs. Now that you are closer to them, the dark shadows really -do- seem to have substance to them. It... it is probably just your imagination. But you think you might have just seen that one breathe. Shadows, you are certain, should not breathe. It takes another second before you rally your flagging nerves and take the first step down, trying to avoid both sides of the corridor, but especially that much too alive shadow. You start down at a slow creep, trying not to disturb the cloying shadows. It feels like they have... substance. Thin, wafting, not much more than mist substance. But substance all the same... \n\nYou bolt down the last handful of steps, bursting out of the shadows and into a corridor. You'd swear something touched your back, but a searching glimpse reveals... stairs. And shadows. But nothing more. You notice there is another set of stairs, equally crowded with overly-present shadows, across from the ones you just descended and you do your level best to watch them both at once, holding your breath and trying to decide what you would do if something actually -did- come out at you. It is a few moments more before you decide they are going to stay put. You pull your eyes away from the shadows to look to the corridor before you. \n\nTo your right is a metal door. Some sort of symbol you don't recognize is carved into the center of it - sharp and angular. Despite the imposing look of the slab of metal, you don't see a lock to keep people out. To your left is a far more unassuming door, standing half opened. You think you see the back of a chair through the opening. Ahead of you, the corridor continues. The shadows you noticed in the floor above seem a bit more populous here. Their color darker, and they are undoubtedly unsettled. You still can't seem to catch them moving, but they seem... restless. What do you do? \n"

lower_corridor_return = "\nYou find yourself standing at the end of the lower corridor. A metal door stands shut to your right. You haven't seen any other metal doors in the fortress - sturdy though many of them are - and this door has a strange symbol carved into the center of it. Ahead of you the corridor continues deeper into the fortress. To your left is a plain wooden door, open just enough to reveal an uninformative section of a dark room - and perhaps a glimpse of a chair? Behind you, the stairs head up from the corridor to your right and left - both staircases still thickly populated by those overly dark, overly tangible shadows... you wish they would find somewhere else to linger. What do you do? \n"

lower_corridor_choices = "\n1. Even if there isn't a lock, a metal door seems sturdy enough to protect a treasure. Maybe you'll check that one out. Head to the right. \n2. Shifty shadows or no, you decide to head further down to corridor to see what else is here. \n3. Go left and check out the plain looking door. \n4. Head upstairs by the right staircase. Try not to let those shadows grab you again! \n5. Head up the left staircase. Preferably quickly. \n"


# LIBRARY

library = "\nYou step up towards the metal door. Up close, it still looks remarkably intact. There isn't any rust or dust to be seen on it. That strange symbol in the center looks like it has been chiseled into the metal by a steady if not expert hand. You kind of hope that's not a magic sigil set to blow someone up. You decide that would probably be too mean, even for whoever lived in this fortress. Though... you glance briefly back to the stairs with the far-too-tangible shadows. Maybe not. You take a deep breath... and push the door open. No explosions, that's good at least. The room beyond is even dimmer than the hallway you just left. But you can make out rows and rows of shelves, stuffed full of scrolls, books and stacks of loose paper. A library perhaps? You creep past the rows, seeing more of the same down each one. As empty as the rest of the fortress is, it seems like no one has touched the library since it was abandoned. A shimmer of something bright catches your eye in the last row. You hesitate a moment before stepping closer to see what it is. A small scroll, not much longer than your hand, is sitting in a rare empty space on a shelf just below eye level. It seems to gleam with a light of its own, a bubble of air around it shimmering faintly. Tied shut with a blue ribbon, there is also a tiny scrap of paper tucked under it with '{0}' written in flowing script. That... that is unusual. You swallow hard and glance left and right. You are pretty sure there is no one else in here; you would have heard them in this eerie quiet, right? Unless it was one of those shadows... But why is your name on this scroll? What do you do? \n"

library_return_with_scroll = "\nYou push open the metal door, noting how smoothly it pivots on its hinges despite the weight of the metal. It's amazing what you take note of when you're not worried about being blasted into pieces. The dark shelves of the library haven't changed from your last visit. Though the dust of ages has settled here as well, it doesn't seem as thick as it is in the other rooms. A peek down the last row shows you a still-empty space where the scroll with your name was sitting. You can just feel its slight weight in your pocket. No new notes from whoever left that one... What do you do? \n"

library_return_no_scroll = "\nYou push open the metal door, noting how smoothly it pivots on its hinges despite the weight of the metal. It's amazing what you take note of when you're not worried about being blasted into pieces. The dark shelves of the library haven't changed from your last visit. Though the dust of ages has settled here, as well, it doesn't seem as thick as it is in the other rooms. A peek down the last row shows you a faint glitter. The scroll you saw earlier is still sitting there. '{0}' inexplicably written on the scrap of paper tucked under the ribbon. What do you do? \n"

library_return_scroll_used = "\nYou push open the metal door, noting how smoothly it pivots on its hinges despite the weight of the metal. It's amazing what you take note of when you're not worried about being blasted into pieces. The dark shelves of the library haven't changed from your last visit. Though the dust of ages has settled here, as well, it doesn't seem as thick as it is in the other rooms. A peek down the last row shows you a still-empty space where the scroll with your name was sitting. You don't know who left it there... but you don't know what would have happened if they hadn't. No new notes from whoever left that one... What do you do? \n"

library_choices = "\n1. You eye the scroll suspiciously, but decide it must have your name on it for a reason. Right? Take the scroll. \n2. Everything in this fortress has been strange and unusual. Maybe it's not worth picking up the strange bit of paper just for the sake of curiosity... Leave the scroll. \n"

library_take_scroll = "\nWhen you reach for the scroll, the shimmering air around it feels slightly warmer than it should... but nothing more seems to come of it. When you lift the scroll from the shelf the shimmers sparkle once and fade and disappear. The scroll is light and seems delicate, but when you pull on the ribbon it refuses to budge. With a faint frown, you tug a bit harder - still nothing. Huh. A few more experimental yanks shows that she scroll is not to be opened despite the force you put into it. Well, you suppose it's not any odder than the rest of this place... What do you do?\n"

library_choices_take_scroll = "\n1. Return to the corridor. There doesn't seem to be anything else for you here.\n"

library_leave_scroll = "\nYou don't think any good can come of a scroll left for you in this place. What if it's a curse? Or booby trapped? Better safe than sorry, after all. What do you do? \n"

library_choices_leave_scroll = "\n1. Nothing more to see here - head back to the corridor. \n2. On the other hand... if does have your name on it. Maybe you'll take the scroll after all. \n"

library_choices_took_scroll = "\n1. It would be nice if this library included a treasure map, and not just mysterious scrolls... Return to the corridor. \n"


# STUDY ROOM

study_room = "\nYou turn your attention to the left and head to the door there. The darkness of the room beyond makes you hesitate a moment before you ease through the half-open wooden door. Like elsewhere in the fortress, the dust has gathered across the flat surfaces in the room. In this case... a series of small tables. Huh. You take another step forward and a single candle sitting on the central table springs to life with a hiss, making you blink and throw up a hand at the sudden gleam of the first real light you have seen since entering the fortress. You drop your hand after a moment as your eyes adjust, glancing around the room. The omnipresent shadows seem smaller here, in the flickering light of the sole candle. Unfortunately, it doesn't reveal anything more in the room than you could already see. Small tables, each with their own chair. A quill lies abandoned on the furthest one, but other than that... more dust. What do you do? \n"

study_room_return_no_candle = "\nThe room is dark once more when you step into it, the small tables still dusty where you left them and the candlestick sitting atop the middle one. Odd. You would have sworn the candle was burning when you left, but now it seems as if it had never been lit. You take a step, hand at the ready as you wait for it to relight. Another step... still nothing. You relax. Maybe you imagined-- as you take a third step the candle bursts alight again, stinging your eyes with its brightness and making you jump. It feels like it did that on purpose... knowing this place as you do now - it probably did. What do you do? \n"

study_room_return_candle = "\nThe room is dark once more when you step into it, the small tables still dusty where you left them save for the ring of melted wax you pulled the candlestick from. Maybe it is your imagination... but do the shadows seem a bit thicker now that you have taken the candle? You consider them a moment before deciding that even if it is so, they seem inclined to stay where they are. What do you do? \n"

study_room_choices = "\n1. Well, nothing to see here. Head back into the corridor. \n2. While the sourceless light of the fortress isn't bad... you wonder if a candle might not be helpful. Grab the candle. \n"

study_room_choices_took_candle = "\n1. There doesn't seem to be much more to see here. Head back into the corridor.\n"

study_room_candle = "\nYou step closer to the table and reach out to grab the pewter candlestick. You frown slightly when it won't move from its spot, and tug a bit harder. Surely a candlestick isn't -that- heavy. And it seems to be getting warmer under your fingers... But you really don't want to leave this spot of light. With a last yank the candlestick pops free of the melted wax that held it tight. And as quickly as it had lit itself, the flame vanishes into a rapidly thinning tendril of smoke, the heat fading away beneath your fingers. Huh. What do you do? \n"

study_room_choices_post_candle = "\n1. What use is an unlit candle? Maybe there's a match here somewhere. Have a look around. \n2. There doesn't seem to be anything else to see. Head back into the corridor. \n"

check_study_room = "\nYou step further into the room, dust rising in silent grey puffs beneath your feet. Further investigation shows you just want you saw from nearer the door, though - scant furniture, a lonely quill and the omnipresent dust of the fortress. There doesn't seem to be anything else to see here What do you do? \n"

study_room_choices_post_check = "\n1. Head back into the corridor. Maybe you can find a match somewhere else instead.\n"


# lOWER HALL

lower_hall = "\nYou head further down the corridor. You steps crunch slightly over bits of stone and rubble scattered through the dust on the floor. The stone down here seems to have suffered a bit more heavily from the passage of age than that of the floor above. Or perhaps it was never as nice to begin with. The corridor empties into a large hall, though this one is rather utilitarian in its design. A few thick, square columns support the roof. The floor is covered with large flagstones, but no artistic flourishes lighten the space down here. You glance up. The ceiling is higher than the corridor, though it certainly doesn't reach the lofty heights you saw upstairs. And it looks like the shadows have taken up residence here, too. Like bats, they scatter over the ceiling, too shifty to be natural. If you hold your breath you think you can almost hear them moving... A shiver runs up your spine and you look away. Maybe they will just be content to leave you be. To your left you see a wooden door standing half open. The room beyond seems rather dark. Ahead is a double-wide opening into another space. And further off to the right you can just see a third door past one of the columns, iron bound and closed tight. What do you do? \n"

lower_hall_return = "\nYou find yourself in the large, open lower hall again. More utilitarian that the fancied-up version upstairs, this lower hall nevertheless serves it purpose: pointing you towards more rooms. You do your best to ignore the shadows clinging thickly to the high (but maybe not high enough for comfort) ceiling. The faint raspy whisper of their shuffling could be your imagination... it could be. To your left you see a wooden door standing half open. The room beyond seems rather dark. Ahead is a double-wide opening into another space. And further off to the right you can just see a third door past one of the columns, iron bound and closed tight. What do you do? \n"

lower_hall_return_open_door = "\nYou find yourself in the large, open lower hall again. More utilitarian that the fancied-up version upstairs, this lower hall nevertheless serves it purpose: pointing you towards more rooms. You do your best to ignore the shadows clinging thickly to the high (but maybe not high enough for comfort) ceiling. The faint raspy whisper of their shuffling could be your imagination... it could be. To your left you see a wooden door standing half open. The room beyond seems rather dark. Ahead is a double-wide opening into another space. And further off to the right you can just see a third door past one of the columns, iron bound and sturdy, hanging wide open now. What do you do? \n"

lower_hall_choices = "\n1. Head left. Best to see what's through a door that's already open, right? \n2. Move through the doorway ahead. Maybe there will be less shadows in an open space at least. \n3. Go right. You can't quite avoid the temptation of a closed door. Maybe you'll finally happen upon the treasure. \n4. Head back down the corridor. \n"


# BARRACKS

barracks = "\nYou head towards the half-open door. It looks sturdy - thick wood bound with iron - but when you push on the door it swings easily open on hinges still silent. You step into the room, and it seems... muffled. Not that there is a lot of sound down in the depths of the fortress, but your steps don't seem as loud in here. There isn't too much to see, though. A lot of tumbled lengths of wood and cloth, mostly. One cot is still standing tremulously under its own weight to the right, and gives you a hint to where you might be. This must have been the barracks once upon a time. You glance to the left and straighten up at the sight of a chest. Could the treasure really be just sitting out on the floor?! You dash down to the chest and tug the lid up. You let out a startled yell as something black and shadowy explodes out of the chest and straight up into your face. For a second it feels as if you have been dipped in icy water before your vision clears and the sensation fades. You stand frozen where you stumbled back from the chest. Was that... one of the shadows? Does it look like there's one more of the things haunting the walls than there was a moment ago? You scrub a hand over your face trying to forget the sensation of it against your skin. Glancing down you see that the chest - without its resident shadow - is woefully empty. Almost. In the corner of the chest is something that looks a bit like a pebble. Upon closer inspection, it seems to be a seed carved out of stone, the tiniest tendril of an unknown plant just sprouting out of a delicately carved crack along the top surface. What do you do? \n"

barracks_return_with_seed = "\nYou step back into the barracks. Despite being as stoney as the rest of the fortress, this room somehow feels quieter than the others. Not like an eerie, uncomfortable quiet, but a soothing one. The cots ravaged by time are evenly spaced through the room, and the chest that held the shadow still stands open where you left it. The shadow doesn't seem to have returned in your absence. You can feel the weight of the stone seed from the chest in your pocket. It seems a strange item to be tucked away down here in a soldier's chest. Maybe it belongs somewhere else... What do you do? \n"

barracks_return_with_key = "\nYou step back into the barracks. Despite being as stoney as the rest of the fortress, this room somehow feels quieter than the others. Not like an eerie, uncomfortable quiet, but a soothing one. The cots ravaged by time are evenly spaced through the room, and the chest that held the shadow still stands open where you left it. The shadow doesn't seem to have returned in your absence. You can feel the weight of the stone key you traded for the seed in your pocket - and you have to wonder what that seed was doing all the way down here in a soldier's chest... guarded by a shadow? Or had that thing gotten stuck by mistake? Who knows. What do you do? \n"

barracks_return_no_seed_or_key = "\nYou step back into the barracks. Despite being as stoney as the rest of the fortress, this room somehow feels quieter than the others. Not like an eerie, uncomfortable quiet, but a soothing one. The cots ravaged by time are evenly spaced through the room, and the chest that held the shadow still stands open where you left it. The shadow doesn't seem to have returned - to the chest or to take the stone seed. The seed still sits in the corner of the otherwise empty chest. What do you do? \n"

barracks_choices = "\n1. You reach down to pick up the seed, hoping the shadow from the box doesn't object to such a thing, before you leave the barracks. \n2. You decide it might be wisest not to mess with whatever had been in that chest - maybe it was attached to the little bit of stone. With a last brush of your face you head back into the hall, keeping an eye out for any more shifty shadows. \n"

barracks_choices_seed_taken = "\n1. You cast a last glance around the room, and at the empty chest, before you head back out into the hall. \n"


# MESS HALL

mess_hall = "\nYou stride across the hall and towards the open doorway. You feel more confident stepping into a space you can see. With no doors to bar the way, you catch sight of a few rows of long tables as your near. It looks like you have found the mess hall. Low benches are tucked under the tables, though a couple nearest the door have been upset and left lying where they fell. The tables are empty, though, save of a healthy (or not so healthy) layer of dust. There's another door in the far corner - probably the kitchen? The blackness through that doorway seems to be infinite and untouched by the sourceless light of the rest of the fortress. That looks exceedingly... unsettling. You imagine it would be seething, if there was any scrap of light to reveal such a detail to you. Surely a treasure wouldn't be stashed in - what, a kitchen? What do you do? \n"

mess_hall_return = "\nYou step into the mess hall again, casting your eyes over the tables and benches. It seems a bit odd for such a room to be so quiet. It should be filled with people and food and pleasant chatter... not dust and silence. Your gaze almost reluctantly touches on what must be a kitchen door, the ominous shadow you saw there hasn't moved. If anything, you wonder if perhaps it is creeping out into the mess hall... Does it seem to be more alive than it should be? What do you do? \n"

mess_hall_return_post_kitchen = "\n something here about how the kitchen is visible/not shadowy"

mess_hall_choices = "\n1. You really, reeeally don't like the look of that impenetrable blackness. But you are going to give it a go all the same. Head towards the kitchen. \n2. No way you are going into that inky blackness. Some things are best left unexplored. Go back to the lower hall.\n"


# KITCHEN

kitchen_no_candle = "\nYou start to second-guess this decision the closer you get to the doorway to what you presume is the kitchen. The darkness beyond that doorway hasn't lightened one bit as you neared. If anything, it seems to have deepened. And seems to be... seeping out into the mess hall. You pause, watching it. Unlike the shadows gathered elsewhere in the fortress you are -positive- you can see this one moving, blindly questing out towards your boots. You take a steadying breath, reminding yourself of the treasure you need to find... and take another step, trying to ignore the vague squishing sensation as you make contact with the shadowy tendril. You... you don't think shadows are supposed to squish. You reach out a hand as you near what seems to be a tangible wall of shadow. Just before you make contact... -something- reaches out to grab back, yanking you bodily into the kitchen. \n\nSadly, there is one less {0} in the world. But it seems unlikely anyone will ever find your unmarked grave in the depths of such an inky, kitchen-dwelling shadow. \n\nThe End. \n"

kitchen = "\nYou start to second-guess this decision the closer you get to the doorway to what you presume is the kitchen. The darkness beyond that doorway hasn't lightened one bit as you neared. If anything, it seems to have deepened. And seems to be... seeping out into the mess hall. You pause, watching it as it seems to streeetch towards your boots. A light would be handy right about now. A suddent thought occurs to you. You pull out the candlestick and glance around, maybe there are some matches here you could light it with. Before you have a chance to go looking, the candle suddenly busts to life, shining brighter than any one candle ought to. The response from the shadow is immediate, it shrinks back into the room, drawing away from the pool of light. You take a tentative step forward and the shadowy surface continues to retreat. Feeling a bit braver you take another two steps, driving the shadows before you. The candlight seems to brighten, spreading further into the room as you go.\n\n Sure enough, you find yourself in a kitchen, just as you thought you might. As you step towards the center, the light reaches out to slide over the walls as the shadow quivers in the corners, before it suddenly retreats in a sharp, violent dash towards a narrow door in the back. A pantry perhaps? At least... it seems content to stay there for now. You set the candle down on a stout, wooden table in the center of the kitchen and take a look around.\n\nThe kitchen - surprisingly - doesn't seem to be dusty at all. The candle light pools warmly over the table, but though it was enough to drive the all-too-tangible shadow into retreat, the rest of the kitchen corners still seem to be populated by its less mobile cousins. The iron stoves and ovens loom darkly against one wall, still and silent, shadows gathered darkly in half-open doors. There's something vaguely threatening about them, though you couldn't say why. Along the other wall tables and tools lay about. There seem to be far more knives than any one kitchen should need, their blades still sharp and bright despite the dust and cobwebs that shroud the deepest corners. You glance back towards the pantry, not forgetting the threat of the living shadow, though it hasn't moved again. A pile of crates further back in the kitchen has tipped over, spilling straw and broken bits of crockery across the floor. There looks to be something bright gleaming from beneath a tattered bit of cloth. What do you do? \n"

kitchen_choices = "\n1. You scared it away once, maybe you can do it again... Take the candle and follow the shadow creature. \n2. Something looks unusual about that gleam of white near the crates. Go check it out. \n3. You're not sure you trust the candle to stay lit or the shadow to stay put... maybe you should get out of here. Head back to the mess hall.\n"

kitchen_return = "\nYou step into the kitchen once more. The candle is still burning brightly, illuminating the wooden table it sits upon. The rest of the room is lit enough to see... but something about it feels dark despite the light. Sharp knives and looming ovens seem to threaten despite being cold and still. It sends a shiver up your spine. But no more than the writhing shadow that lingers in the pantry at the back of the kitchen. It doesn't seem keen on coming out into the light, but you can't help but feel like it's just waiting for a chance to grab you... Aside from the abandoned knives, there doesn't seem to be much left in the kitchen aside from dust and a spilled pile of crates. What do you do? \n"

pantry_sudden_death = "\nYou pick up the candle, taking a deep breath. You still don't like the look of that shadowy thing... but you know now that it doesn't like the candle light. Who knows, maybe it is guarding the treasure back there? You march yourself towards the pantry door, holding the candle out in front of you. As you near the shadow shrinks back again, much to your relief - however brave you were feeling when you decided to see what it was hiding. But... as you step into the doorway, easing the pantry door the rest of the way open to look inside... the shadow doesn't seem to be retreating anymore. You have a brief glimpse of a small room, lined with dusty shelves where the shadow isn't pressed agains them, before the shadow lets out a shriek far beyond the range of human hearing, but that you nevertheless feel vibrating against you. The rustling sound of shadows swells rapidly behind you and you spin around to see a wave of the living shadows swarming towards the call. Rushing to protect their mother driven into a corner by your light. You lift the candle, but they don't even hesitate, flinging themselves at you and the light, smothering it and you together. \n\n Sadly, there is one less {0} in the world. But it seems unlikely anyone will know where to look for you in the deepest, darkest shadows of the fortress. \n\nThe End. \n"

kitchen_boxes = "\nYou step a bit further into the kitchen, keeping a wary eye on the shadow beast lurking in the pantry. While you can see it shifting about... it doesn't seem willing to leave the pantry. You turn your attention to the crates as you near them. There doesn't seem to be much to see. Once they must have held bowls and plates for the mess hall behind you, but as the wood rotted and splintered the pottery dishes fell and shattered, shards of them crunching beneath your feet as you step through them. But, there is that one bright gleam of white that caught your eye from across the room. You cast about for it, catching sight of the tattered cloth among the spilled crockery and straw. What do you do? \n"

kitchen_boxes_choices = "\n1. It couldn't hurt to see what it is. Pick it up. \n2. Hm. Maybe it's best not to mess with it - you don't want to provoke the shadow. Head back. \n"
#finish these up - also add the bits about returning to the kitchen with/without the figurine being taken
kitchen_figurine = "\n"


# TRAPDOOR ROOM

trapdoor_room = "\nYou head past the sturdy columns towards the closed door at the far end of the hall. You can't help but glance up now and again as you walk - there is a faint, skittery stirring to the shadows clinging to the ceiling as you get closer to the door. Each time you glance up it seems as if they are crowded more thickly above you... as long as they stay up there. You hope fervently that they do. Luck seems to be on your side, though. Despite the faint noises of them following you, they do seem to have stayed on the ceiling. You glance up one last time before reaching out to try the door. The handle turns, but the door seems to be stuck. You push against it and it slides a reluctant half inch. Another shove convinces it to move an additional quarter of an inch. Great. You take a step back and throw your weight into the wooden barrier and it gives way in a split second, rebounding back against the stone with a ~BANG~ that echoes through the fortress, even as you do an exceedingly elegant almost-faceplant into the floor. \n\nIt doesn't take you long to spring back to your feet, though, gaze fixed on the door you just fell through. More than your newly bruised knees, you worry about the resounding echo still fading too slowly as it reverberates through the stone rooms and halls. And with it comes a no longer subtle skittering of... something... shadows? ... moving through the fortress. You hold your breath, but nothing appears. After the longest few seconds of your life, the sound grows quieter and disappears. It's another minute before you dare to move. Maybe you should hurry up and find the treasure. You thought it would be safer in here than out in the Haunted Weald... but you are less certain of that now. You glance quickly around the room, at first thinking you had risked all that for nothing more than a small, bare chamber. But then you see the trapdoor. Similar to the door, the solid wood is iron bound and set into the very center of the floor in the square room. Probably a good place to hide a treasure, right? What do you do? \n"

trapdoor_room_return_closed = "\nYou step into the small, bare room. There isn't much to see aside from stone it is built from. And a very closed, very secure trapdoor. It might have been too much to hope that it would be mysteriously open upon your return. Iron-bound and solid wood of what you can only imagine is an impressive thickness... It must be hiding something important. What do you do? \n"

trapdoor_room_return_opened = "\nYou look around the small, bare room. There isn't much to see aside from stone. The trapdoor is still open, tiny metal scraps of the crowbar you used to pry it open scattered through the dust, catching a faint glint of the sourceless light now and again. What do you do? \n"

trapdoor_room_choices = "\n1. You came here looking for a treasure right? So why don't we see what's down there. Open the trapdoor. \n2. After whatever that skittering was, maybe you're not quite ready to head any deeper into this creepy fortress... go back to the lower hall.\n"

trapdoor_room_choices_open = "\n1. Head through the trapdoor and down the ladder. \n2. Return to the lower hall through the door instead.\n"

opening_trapdoor = "\nThe trapdoor is stubbornly wedged in place - age doesn't seem to have weakened the wood. If anything it has made the thing more difficult to get through. Luckily, you came prepared. You pull out the crowbar you found upstairs and throw your weight into prying the door open. The trapdoor resists, before it slowly starts to shift with an audible groan of protest. Then, with a thunderous snap and the sharp clatter of metal on stone, the door pops open. Your trusty crowbar, sadly, gave its life for the task. It didn't seem to have aged as well as the trapdoor itself. "

trapdoor_no_crowbar = "\nYou push and pull and tug and stomp; you even try politely, and not so politely, asking the thing to open. But the trapdoor absolutely refuses to budge. If it had a face you imagine it would be laughing at your efforts. Maybe you need something to pry it open with... "


# TUNNEL

base_of_ladder = "\nWhile you are glad to have gotten the door open, your heart almost leaps into your chest at the sound it came with. You decide it is best not to wait and see if the skittering returns, perhaps with something unpleasant to follow, and hurry through the trapdoor. You find a ladder, which creaks alarmingly under your weight, although it seems to be intact, and you quickly make your way down... and down... and down it. You drop to a stone floor, relieved the ladder actually had an end. A glance back up the ladder shows nothing following you down... that's good at least. The odd illumination of the fortress seems to extend down here - if anything it is a little brighter, a cool blue hue suffusing what you now can see is a stone tunnel. You don't seem to be in the fortress itself anymore, but instead in a path burrowed into the bedrock itself. The tunnel extends in either direction, but you can't see anything other than stone in either direction. What do you do? \n"

base_of_ladder_return = "\nYou find yourself at the base of the ladder leading up into the fortress. A glance up shows a narrow, longer-than-seems-reasonable tunnel carved through the solid stone, leading up to the lower floors of the fortress. The stone tunnel you are standing in is equally nondescript, though a bit bigger in scale. It extends to both the left and the right, with nothing to differentiate the two paths from one another save their directions. What do you do? \n"

base_of_ladder_choices = "\n1. With a mental flip of a coin, you decide to head left. It seems as good a direction as the other. \n2. You glance one way and then the other. Why not right? Head that way. \n3. Hm. Deep dark tunnels under an abandoned fortress? Maybe not. Head back up the ladder.\n"

base_of_ladder_choices_survivor = "\n1. Yeah, tunnel to the left? Not such a fun one the first time... Check it out again? \n2. Head to the right and see where that tunnel leads you... \n3. Hm. Deep dark tunnels under an abandonded fortress? No thanks. Head back up the ladder. \n"

sudden_death_scroll = "\nYou start left down the tunnel. It seems pretty unremarkable for the most part - just more stone, the uneven walls of the tunnel unrelieved by any openings or doors. The soft crunch of dirt and grit under your boots accompanies your steps. And then - a crack. You pause. It almost sounds like that first step you take onto lake ice when it isn't quite frozen enough to support your weight... You start to ease your weight back... and then there is another crack. And another. Before you have time to retreat any further, the stone of the floor gives way entirely with the clattering rumble of stone falling against stone and a huge splash as it crashes into a rushing underground river scant feet below you. You stare down at the river-- \n\n--finding yourself, improbably, floating mid-air above the gaping hole in the tunnel floor. You drift back over stable stone, before whatever it was that held you suspended drops you back to the ground. You promptly feel a burning sensation in your pocket which makes you jump before you rapidly fish out the small scroll you picked up earlier... just in time to watch it charring into ash before your eyes. You try not to think too hard about what might have happened if you hadn't picked that up... You glance once more into the rushing waters below before you hurry back towards the ladder. "

sudden_death_no_scroll = "\nYou start left down the tunnel. It seems pretty unremarkable for the most part - just more stone, the uneven walls of the tunnel unrelieved by any openings or doors. The soft crunch of dirt and grit under your boots accompanied your steps. And then - a crack. You pause. It almost sounds like that first step you take onto lake ice when it isn't quite frozen enough to support your weight... You start to ease your weight back... and then there is another crack. And another. Before you have time to retreat any further, the stone of the floor gives way entirely with the clattering rumble of stone falling against stone and a huge splash as it - and you - crash into a rushing underground river running scant feet below the tunnel. You are sucked down below the stone with the waters of the river, but no matter how hard you scrabble to escape the waters, it seems like there is no more air to be found in the dark, watery path. \n\nSadly, there is one less {0} in the world. But it seems unlikely anyone will ever find your unmarked grave in the depths of this underwater river. \n\nThe End. \n"


# TREASURE ROOM

treasure_room = "\nYou head right down the stone tunnel. For a while there is little to see aside from more stone. Eventually, though, the blue light seems to intensify as you pass twists and turns. With no warning, you are dumped out into a massive cavern. You stop two steps in to stare. The whole cave is covered in shimmering crystals, which seem to be the source of the blue light illuminating the space. The cave is bigger than any of the halls you found in the fortress above, and you can't quite tell how far back it goes... it seems to be endless for all you can see. The walls are studded with perfectly shaped crystals, but the most fantastic elements are the sweeping formations of what would have been stone in any other cave and instead here are cast in beautiful, glittering crystal. Staggeringly large stalactites, elegant ribbon formations, sparkling columns. It's stunning. It's almost enough to distract you from what else is in the room: a chest that would be large anywhere else but is small in comparison to the rest of the cave. Could this finally be the treasure you were sent here for? You head towards the chest, trying not to be distracted by the sights around you. What do you do? \n"

treasure_room_return = "\nThe abrupt transition from dark stone tunnel to glittering underground cave is just as astounding as it was the first time. Even if you have already stared once, your eyes linger on the glittering crystal formations of the cave, elegant and fragile in appearance, though their staggering size would argue otherwise. You walk between them, managing - just - to pull your eyes back down to the ground. And to the lone chest sitting in the center of the floor. It seems like an unusual place to store a treasure - in a chest, all by itself, in the middle of such a breathtaking cave... but here you are all the same. What do you do? \n"

treasure_room_chest = "\nCloser examination of the chest reveals a keyhole in the center of the lid. Maybe you can get it open anyways... it's been down here for ages anyways, right? You push and tug and kick and even try asking it nicely (and not so nicely) to open. Seems like they had immpecable craftsmanship back in the day. Perhaps the key was left behind somewhere in the fortress...\n"

treasure_room_choices = "\n1. Finally! Time to get the treasure and get out of this creepy fortress! Open the chest. \n2. Head back to the base of the ladder. \n"

treasure_retrieval = "\nAs you get closer to the chest, you notice that there is a keyhole in the center of the lid. It is oddly similar to something you have seen before... in fact. You pull out the key that was held in the hand of the goddess, and see that the black stone is identical. You fit the key into the lock and turn it. With a gentle click the lid of the chest pops open. Finally! You push the lid open and see... \n\n...and see a lunchbox. What? Surely this can't be the treasure. And what in the world is a lunchbox doing here of all places? You hesitantly reach down and pick it up. The metal lunchbox is decorated with cartoon super heroes. The bright colors are the most brilliant things you have seen since finding yourself in the forest. You open the lid and see a handwritten note on top of what appears to be a neatly packed lunch. You can't help but notice that the handwriting is the same as that on the scroll you found...\n\n      'My dearest love, \n       I hope that you managed to survive the forest, the kitchen (don't touch my pots again), and the pit (I warned you not to dig yourself too deep). Here's your lunch. I didn't poison anything, though a little upset stomach would probably be well deserved. \n                Love, \n                Your most beautiful, astounding, patient wife <3' \n\nAs you stare at the note, the glimmering cave around you fades away. It is replaced with a far less resplendent, but far more familiar kitchen. You are standing in front of the open refrigerator holding your lunchbox. Memories are quick to resurface. You had an argument with your wife last night. It definitely started with the dishes (it was hard to remember which pots were the non-stick pots...) and disintegrated from there. Everyone tried to warn you marrying a witch would come with its unique trials... but. At least you survived this time. And you still got lunch! You'd better not touch the pots again, though, if you expect to survive the next argument... \n\nThe End. \n"

